rw = room_width
rh = room_height
dialog_off = 1
button_icon_offset = 0
depth = -999
vx = __view_get(0, 1)
vy = __view_get(1, 1)
vw2 = __view_get(2, 0)
vw = __view_get(2, 0)
vh = __view_get(3, 0)
linesvisible = 1
dialog_mode = 0
dialog_portrait = 356
dialog_portrait_index = 0
dialog = ""
dialogtemp = ""
dialogsound = 230
dialogfeedtimer = 0
dialogchatcounter = 0
dialogsnapped = 0
dialogposition = 0
dialog_box_height = 42
hudhide = 0
hpreadout = 0
dialog_style = "normal"
dialog_style_wavy_angle = 0
dialog_style_wavy_mag = 1
dialog_style_wavy_spread = 0.5
dialog_style_wavy_speed = 0.05
