checked = 0
prop_cur = 0
message[0] = "Intro Area"
message[1] = "Aqueduct"
message[2] = "Hub World"
message[3] = "Heater Core"
message[4] = "Ventilation"
message[5] = "Incubator"
message[6] = "Laboratory"
property[0] = "map0"
property[1] = "map1"
property[2] = "map2"
property[3] = "map3"
property[4] = "map4"
property[5] = "map5"
property[6] = "map6"
image_speed = 0
prop_cur = real(string_copy(MAP_MANAGER.map_current, 4, 1))
button[0] = instance_create(x, y, obj_editor_button0)
button[0].sprite_index = spr_editor_arrow
button[0].text = ""
button[0].host = id
button[0].key_target = 109
button[1] = instance_create((x + 16), y, obj_editor_button0)
button[1].sprite_index = spr_editor_arrow
button[1].image_xscale = -1
button[1].text = ""
button[1].host = id
button[1].key_target = 107
