sample_w = 1
sample_h = 1
target_x_centered = 288
target_x = target_x_centered
x = target_x + 320
xstart = x
y = 64
approach_speed = 4
ticker = 180
scale = 8
sampleRate = 0.1
tex = sprite_get_texture(sprite_index, 0)
rng = 0
