new_game = 0
state = 3
audio_play_sound(snd_menu_select, 5, false)
sub_cursor_index = 0
sub_entries = 3
fselectoptions_header = ""
fselectoptions = -1
fselectoptions_text = -1
fselectoptions_text[0] = loc_read_line(557)
fselectoptions[0] = 640
fselectoptions_text[1] = loc_read_line(558)
fselectoptions[1] = 637
fselectoptions_text[2] = loc_read_line(549)
fselectoptions[2] = 633
