draw_set_font(global.font[global.language])
draw_set_halign(fa_center)
draw_set_valign(fa_middle)
draw_frame2(134, 76, 294, 116)
draw_text((214 - (key_cursor < 4) * 4), 86, key_name[clamp(key_cursor, 0, 8)])
if (key_cursor < 4)
    draw_sprite(spr_directions, key_cursor, (210 + (string_width(key_name[max(0, key_cursor)])) / 2 + 6), 86)
if (key_cursor > -1 && wait_timer)
    draw_text(214, 100, string_keycheck(keys_selected[key_cursor]))
if (!wait_timer)
    draw_text(214, 126, message_key_press)
draw_set_halign(fa_left)
draw_set_valign(fa_top)
