event_inherited()
inactive = 0
sidewall_a = instance_create((x - 7), (y + 24), obj_wall2)
sidewall_a.image_xscale = 0.125
sidewall_a.image_yscale = 4
sidewall_a.visible = false
sidewall_a.open_hp = 7
sidewall_a.open_hp_old = 7
sidewall_a.c_destroy = 1
sidewall_b = instance_create((x + 23), (y + 24), obj_wall2)
sidewall_b.image_xscale = 0.125
sidewall_b.image_yscale = 4
sidewall_b.visible = false
sidewall_b.open_hp = 7
sidewall_b.open_hp_old = 7
sidewall_b.c_destroy = 1
bottom = instance_create((x + 8), (y + 52.5), obj_wall)
bottom.image_xscale = 1.875
bottom.image_yscale = 0.4375
bottom.visible = false
top = instance_create((x + 8), (y - 1.5), obj_wall)
top.image_xscale = 2
top.image_yscale = 0.8125
top.visible = false
water = -1
water[0] = instance_create(x, (y + 16), obj_lavacen)
water[1] = instance_create((x + 16), (y + 16), obj_lavacen)
water[2] = instance_create(x, (y + 32), obj_lavadeep)
water[3] = instance_create((x + 16), (y + 32), obj_lavadeep)
water[4] = instance_create(x, (y + 48), obj_lavadeep)
water[5] = instance_create((x + 16), (y + 48), obj_lavadeep)
bubble_timer = wrap((instance_number(obj_lab_tube) * 10), 10, 30)
bubble_timer_max = 30
depth = water[0].depth - 1
