var temp = instance_create((x - (x - xprevious) * 4), (y - (y - yprevious) * 4), obj_rocketrail)
temp.image_angle = image_angle
image_index = 1
temp.depth = depth + 1
temp = instance_create(xprevious, yprevious, obj_rocketrail)
temp.image_angle = image_angle
image_index = 2
temp.depth = depth + 2
alarm[2] = 1
