event_inherited()
if (muzzle_l > -1)
    draw_sprite_ext(spr_muzzle_lg, muzzle_l, (x - 11), (y + 50), 1, 1, 270, c_white, 1)
if (muzzle_r > -1)
    draw_sprite_ext(spr_muzzle_lg, muzzle_r, (x + 13), (y + 50), 1, 1, 270, c_white, 1)
