if (muzdir == "right")
    draw_sprite(spr_muzzle, iindex, (obj_player.x + offset_x), (obj_player.y + offset_y))
if (muzdir == "left")
    draw_sprite(spr_muzzleL, iindex, (obj_player.x + offset_x), (obj_player.y + offset_y))
if (muzdir == "upR")
    draw_sprite(spr_muzzleU, iindex, (obj_player.x + offset_x), (obj_player.y + offset_y))
if (muzdir == "upL")
    draw_sprite(spr_muzzleU, iindex, (obj_player.x + offset_x), (obj_player.y + offset_y))
if (muzdir == "downR")
    draw_sprite(spr_muzzleD, iindex, (obj_player.x + offset_x), (obj_player.y + offset_y))
if (muzdir == "downL")
    draw_sprite(spr_muzzleD, iindex, (obj_player.x + offset_x), (obj_player.y + offset_y))
if (muzdir == "down")
    draw_sprite(spr_muzzleD, iindex, (obj_player.x + offset_x), (obj_player.y + offset_y))
